// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementService.Data;

#nullable disable

namespace TaskManagementService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("TaskManagementService.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(650)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 22, 21, 55, 774, DateTimeKind.Utc).AddTicks(8462),
                            Description = "Create house price prediction model using supervised machine learning techniques.",
                            DueDate = new DateTime(2026, 2, 1, 22, 21, 55, 774, DateTimeKind.Utc).AddTicks(8449),
                            EstimatedHours = 13,
                            Priority = 1,
                            Status = 2,
                            Title = "Learn Supervised Machine Learning",
                            UpdatedAt = new DateTime(2026, 1, 27, 22, 21, 55, 774, DateTimeKind.Utc).AddTicks(8463)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 22, 21, 55, 774, DateTimeKind.Utc).AddTicks(8470),
                            Description = "Analyze sales data using Python libraries such as Pandas and Matplotlib. Then use the data in one of frontend projects.",
                            DueDate = new DateTime(2026, 2, 4, 22, 21, 55, 774, DateTimeKind.Utc).AddTicks(8469),
                            EstimatedHours = 20,
                            Priority = 2,
                            Status = 1,
                            Title = "Complete Python Data Analysis Project"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 28, 22, 21, 55, 774, DateTimeKind.Utc).AddTicks(8476),
                            Description = "Develop a full-stack web application using ASP.NET Core for the backend and React for the frontend. Implement CRUD operations and user authentication.",
                            DueDate = new DateTime(2026, 1, 31, 22, 21, 55, 774, DateTimeKind.Utc).AddTicks(8474),
                            EstimatedHours = 15,
                            Priority = 3,
                            Status = 1,
                            Title = "Create one full-stack project by using ASP.NET Core and React!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
